name: Setup
description: Install Node, pnpm, and dependencies.

inputs:
  install-deps:
    description: Whether to install dependencies or not.
    required: false
    default: 'true'

runs:
  using: composite

  steps:
    - name: Enable corepack
      run: corepack enable
      shell: bash

    - name: Setup node & pnpm
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        check-latest: true
        cache: pnpm

    - name: Install dependencies
      if: ${{ inputs.install-deps == 'true' }}
      run: pnpm install
      shell: bash
