name: ✨ Feature request
description: Suggest a feature that will improve egytech.fyi website.
title: '[Feature]: '
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Before requesting a feature, please make sure that you have read through our [contribution guide](https://egytech-fyi.pages.dev/community/contribute) and existing [issues](https://github.com/egytech-fyi/egytech-fyi/issues).

  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what you think would be an helpful addition to the website, including the possible use cases and alternatives you have considered.
    validations:
      required: true

  - type: textarea
    id: additonal
    attributes:
      label: Additional context
      description: If applicable, add any other context or screenshots here.

  - type: checkboxes
    attributes:
      label: Additional information
      description: Additional information that helps us decide how to proceed.
      options:
        - label: I intend to submit a PR to implement this feature.
