name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  format:
    # Run only on push as we're running autofix.ci on pull requests
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4

      - name: Setup (Install Node, pnpm, and dependencies)
        uses: ./.github/actions/setup

      - name: Format
        run: pnpm run format

  lint:
    # Run only on push as we're running autofix.ci on pull requests
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4

      - name: Setup (Install Node, pnpm, and dependencies)
        uses: ./.github/actions/setup

      - name: Lint
        run: pnpm run lint
