name: autofix.ci # Required (https://autofix.ci/setup)

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  update-contributors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4

      - name: Setup (Install Node, pnpm)
        uses: ./.github/actions/setup
        with:
          install-deps: false

      - name: Update contributors
        run: pnpm run automd

      - name: Push Updates
        uses: autofix-ci/action@v1.3
        with:
          commit-message: 'chore: update contributors'
